Ecto.Adapters.SQL.Sandbox.mode(VBT.TestRepo, :manual)
Mox.defmock(VBT.TestAwsClient, for: ExAws.Behaviour)
Application.ensure_all_started(:credo)
ExUnit.start()
VBT.Absinthe.Instrumentation.set_long_operation_threshold(:infinity)
